# Generated by Django 4.0.6 on 2022-07-12 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_blog', '0002_tag_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publish_date',
            new_name='created_on',
        ),
    ]
