# Generated by Django 4.0.6 on 2022-07-12 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_blog', '0004_alter_post_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published',
        ),
    ]
