# Generated by Django 4.0.6 on 2022-07-12 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_blog', '0005_remove_post_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.CreateModel(
            name='Uper_Line_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uper_content', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexus_blog.post')),
            ],
        ),
        migrations.CreateModel(
            name='Tags_Line_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags_content', models.CharField(max_length=400)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexus_blog.post')),
            ],
        ),
        migrations.CreateModel(
            name='Middle_Line_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_content', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexus_blog.post')),
            ],
        ),
        migrations.CreateModel(
            name='Lower_Line_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_content', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexus_blog.post')),
            ],
        ),
        migrations.CreateModel(
            name='Content_Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_img', models.ImageField(upload_to='Blog/Content_Img')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexus_blog.post')),
            ],
        ),
    ]
