# Generated by Django 4.0.6 on 2022-07-12 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_blog', '0006_remove_post_content_uper_line_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lower_line_content',
            name='post',
        ),
        migrations.RemoveField(
            model_name='middle_line_content',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='tags_line_content',
            name='post',
        ),
        migrations.RemoveField(
            model_name='uper_line_content',
            name='post',
        ),
        migrations.DeleteModel(
            name='Content_Img',
        ),
        migrations.DeleteModel(
            name='Lower_Line_Content',
        ),
        migrations.DeleteModel(
            name='Middle_Line_Content',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Tags_Line_Content',
        ),
        migrations.DeleteModel(
            name='Uper_Line_Content',
        ),
    ]
