# Generated by Django 4.0.6 on 2022-07-12 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nexus_blog', '0009_remove_lower_line_content_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=200)),
                ('header_image', models.ImageField(upload_to='Header/Blog_Page_Img')),
            ],
        ),
        migrations.CreateModel(
            name='Tags_Line_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags_content', models.CharField(max_length=400)),
                ('blog_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexus_blog.blog_page')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('blogs_img', models.ImageField(upload_to='Blog/Blog_Img')),
                ('uper_content', models.TextField()),
                ('middle_content', models.TextField()),
                ('content_img', models.ImageField(upload_to='Blog/Content_Img')),
                ('lower_content', models.TextField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='nexus_blog.tag')),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
