# Generated by Django 4.0.6 on 2022-07-13 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_blog', '0012_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentpost',
            new_name='post',
        ),
    ]
