# Generated by Django 4.0.6 on 2022-07-14 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_blog', '0013_rename_commentpost_comment_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
