# Generated by Django 4.0.6 on 2022-07-15 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_blog', '0018_remove_comment_reply_comment_parent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
