# Generated by Django 4.0.6 on 2022-07-15 10:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_blog', '0022_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='lower_content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='middle_content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='uper_content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
