# Generated by Django 4.0.6 on 2022-07-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_blog', '0023_alter_blog_lower_content_alter_blog_middle_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
