# Generated by Django 4.0.6 on 2022-07-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200)),
                ('icon_class_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Services_Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('paragraph', models.CharField(max_length=1000)),
            ],
        ),
    ]
