# Generated by Django 4.0.6 on 2022-07-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0002_department_card_services_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department_card',
            name='icon_class_name',
        ),
    ]
