# Generated by Django 4.0.6 on 2022-07-06 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0003_remove_department_card_icon_class_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department_Card',
        ),
    ]
