# Generated by Django 4.0.6 on 2022-07-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0004_delete_department_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200)),
                ('icon_name', models.CharField(max_length=1000)),
            ],
        ),
    ]
