# Generated by Django 4.0.6 on 2022-07-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0006_rename_icon_name_department_card_icon_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200)),
                ('icon_class_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameModel(
            old_name='Department_Card',
            new_name='Services_Department_Card',
        ),
    ]
