# Generated by Django 4.0.6 on 2022-07-06 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0007_services_feedback_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services_Feedback',
        ),
    ]
