# Generated by Django 4.0.6 on 2022-07-07 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0009_services_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services_Feedback',
            new_name='GP_Services_Feedback',
        ),
    ]
