# Generated by Django 4.0.6 on 2022-07-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0010_rename_services_feedback_gp_services_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fun_Facts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('mobileno', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('bg_image', models.ImageField(upload_to='Fun_facts_Img')),
                ('sub_title', models.CharField(max_length=500)),
                ('paragraph', models.CharField(max_length=1000)),
                ('buttontext', models.CharField(max_length=100)),
                ('satisfied_clients_count', models.IntegerField()),
                ('world_awards_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='Patient_Img')),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Video_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='Video_Banner')),
                ('paragraph', models.CharField(max_length=1000)),
                ('buttontext', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
