# Generated by Django 4.0.6 on 2022-07-07 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0011_fun_facts_patient_testimonial_video_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fun_facts',
            name='buttontext',
        ),
    ]
