# Generated by Django 4.0.6 on 2022-07-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0012_remove_fun_facts_buttontext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opening_Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('paragraph', models.CharField(max_length=1000)),
                ('day_to_day1', models.CharField(max_length=200)),
                ('time_to_time1', models.CharField(max_length=200)),
                ('day_to_day2', models.CharField(max_length=200)),
                ('time_to_time2', models.CharField(max_length=200)),
            ],
        ),
    ]
