# Generated by Django 4.0.6 on 2022-07-08 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0014_about_us_mission_section_care_provider_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Paragrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='About_Us_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=200)),
                ('header_image', models.ImageField(upload_to='Header/About_Img')),
                ('image1', models.ImageField(upload_to='About_Img')),
                ('image2', models.ImageField(upload_to='About_Img')),
                ('paragraph_Mission', models.TextField()),
                ('paragraph_Care_Provider', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Care_Provider_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_member_photo', models.ImageField(upload_to='About_Img/Team_Img')),
                ('team_member_name', models.CharField(max_length=200)),
                ('department_name', models.CharField(max_length=200)),
                ('about_us_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexus_health.about_us_page')),
            ],
        ),
        migrations.CreateModel(
            name='Mission_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=200)),
                ('about_us_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexus_health.about_us_page')),
            ],
        ),
        migrations.RemoveField(
            model_name='care_provider_section',
            name='about_us',
        ),
        migrations.RemoveField(
            model_name='mission_section',
            name='about_us',
        ),
        migrations.DeleteModel(
            name='About_Section',
        ),
        migrations.DeleteModel(
            name='About_Us',
        ),
        migrations.DeleteModel(
            name='Care_Provider_Section',
        ),
        migrations.DeleteModel(
            name='Mission_Section',
        ),
        migrations.AddField(
            model_name='about_paragrap',
            name='about_us_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexus_health.about_us_page'),
        ),
    ]
