# Generated by Django 4.0.6 on 2022-07-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0015_about_paragrap_about_us_page_care_provider_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Join_Our_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('paragraph', models.TextField()),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
