# Generated by Django 4.0.6 on 2022-07-08 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0017_resources_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resources_Page',
        ),
    ]
