# Generated by Django 4.0.6 on 2022-07-08 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0018_delete_resources_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=200)),
                ('header_image', models.ImageField(upload_to='Header/Resources_Page_Img')),
                ('header_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Resources_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Resources_Img')),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('resources_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexus_health.resources_page')),
            ],
        ),
    ]
