# Generated by Django 4.0.5 on 2022-07-09 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0022_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Appointment_Page',
        ),
    ]
