# Generated by Django 4.0.5 on 2022-07-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0024_appointment_page_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phoneno',
            field=models.CharField(max_length=10),
        ),
    ]
