# Generated by Django 4.0.6 on 2022-07-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0030_alter_appointment_dayofweek_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='dayofweek',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='timeofday',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='waytoreach',
            field=models.CharField(choices=[('phone', 'Phone'), ('email', 'Email')], default=1, max_length=200),
        ),
    ]
