# Generated by Django 4.0.6 on 2022-07-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0032_alter_appointment_dayofweek_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='dayofweek',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], max_length=100, null=True),
        ),
    ]
