# Generated by Django 4.0.6 on 2022-07-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0033_alter_appointment_dayofweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='dayofweek',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='timeofday',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon')], max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='waytoreach',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Email', 'Email')], max_length=100),
        ),
    ]
