# Generated by Django 4.0.6 on 2022-07-10 12:45

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0035_alter_appointment_dayofweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='timeofday',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon')], max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='waytoreach',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Phone', 'Phone'), ('Email', 'Email')], max_length=100),
        ),
    ]
