# Generated by Django 4.0.6 on 2022-07-10 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0036_alter_appointment_timeofday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_Partners_Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partners_image', models.ImageField(upload_to='Header/Our_Partners_Img')),
                ('partners_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexus_health.partners_page')),
            ],
        ),
        migrations.CreateModel(
            name='Our_Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Header/Our_Partners')),
                ('title', models.CharField(max_length=200)),
                ('paragraph', models.TextField()),
                ('link', models.CharField(max_length=200)),
                ('partners_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexus_health.partners_page')),
            ],
        ),
    ]
