# Generated by Django 4.0.6 on 2022-07-11 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0037_our_partners_img_our_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=400)),
                ('department_name', models.CharField(max_length=400)),
                ('experience', models.CharField(max_length=400)),
                ('loction', models.CharField(max_length=400)),
                ('satus', models.CharField(max_length=400)),
                ('rating', models.CharField(max_length=200)),
                ('posting_date', models.DateField()),
                ('last_date', models.DateField()),
                ('job_description', models.TextField()),
                ('careers_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexus_health.careers_page')),
            ],
        ),
        migrations.CreateModel(
            name='All_Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=400)),
                ('link', models.CharField(max_length=200)),
                ('careers_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexus_health.careers_page')),
            ],
        ),
    ]
