# Generated by Django 4.0.6 on 2022-07-11 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0038_job_post_all_departments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job_Post',
        ),
    ]
