# Generated by Django 4.0.6 on 2022-07-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0040_job_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Application_Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phoneno', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='careers/Job_Application_Forms')),
            ],
        ),
    ]
