# Generated by Django 4.0.6 on 2022-07-11 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0042_contact_now_delete_contact_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=200)),
                ('header_image', models.ImageField(upload_to='Header/Contact_Page_Img')),
                ('contact_now_pargraph', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneno', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address_l1', models.CharField(max_length=400)),
                ('address_l2', models.TextField()),
                ('contact_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexus_health.contact_page')),
            ],
        ),
    ]
