# Generated by Django 4.0.6 on 2022-07-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0043_contact_page_contact_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_details',
            name='phoneno',
            field=models.CharField(max_length=100),
        ),
    ]
