# Generated by Django 4.0.6 on 2022-07-11 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0044_alter_contact_details_phoneno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_Details',
        ),
    ]
