# Generated by Django 4.0.6 on 2022-07-11 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0045_delete_contact_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneno1', models.CharField(max_length=100)),
                ('phoneno2', models.CharField(max_length=100)),
                ('email1', models.EmailField(max_length=254)),
                ('email2', models.EmailField(max_length=254)),
                ('address_l1', models.CharField(max_length=400)),
                ('address_l2', models.TextField()),
                ('contact_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexus_health.contact_page')),
            ],
        ),
    ]
