# Generated by Django 4.0.6 on 2022-07-12 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0046_contact_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog_Page',
        ),
    ]
