# Generated by Django 4.0.6 on 2022-07-15 10:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0047_delete_blog_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_paragrap',
            name='paragraph',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='about_us_page',
            name='paragraph_Care_Provider',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='about_us_page',
            name='paragraph_Mission',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='fun_facts',
            name='paragraph',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='gp_services_feedback',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='homebanner1',
            name='paragraph',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='job_post',
            name='job_description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='join_our_team',
            name='paragraph',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='opening_hours',
            name='paragraph',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='our_partners',
            name='paragraph',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='patient_testimonial',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='services_department',
            name='paragraph',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='video_section',
            name='paragraph',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
