# Generated by Django 4.0.6 on 2022-07-18 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0048_alter_about_paragrap_paragraph_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job_Application_Forms',
        ),
    ]
