# Generated by Django 4.0.6 on 2022-07-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0050_job_application_forms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_application_forms',
            name='job_profile',
            field=models.CharField(max_length=200),
        ),
    ]
