# Generated by Django 4.0.6 on 2022-07-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0051_alter_job_application_forms_job_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_application_forms',
            old_name='job_profile',
            new_name='job_title',
        ),
    ]
