# Generated by Django 4.0.6 on 2022-07-18 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0052_rename_job_profile_job_application_forms_job_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_application_forms',
            old_name='job_title',
            new_name='jobtitle',
        ),
    ]
