# Generated by Django 4.0.6 on 2022-07-18 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0053_rename_job_title_job_application_forms_jobtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_application_forms',
            old_name='jobtitle',
            new_name='job_profile',
        ),
    ]
