# Generated by Django 4.0.6 on 2022-07-18 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0055_rename_job_profile_job_application_forms_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_application_forms',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post', to='nexus_health.job_post'),
        ),
    ]
