# Generated by Django 4.0.6 on 2022-07-18 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_health', '0056_alter_job_application_forms_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_post',
            name='careers_page',
        ),
        migrations.DeleteModel(
            name='Job_Application_Forms',
        ),
        migrations.DeleteModel(
            name='Job_Post',
        ),
    ]
