# Generated by Django 4.0.6 on 2022-07-18 10:06

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nexus_health', '0057_remove_job_post_careers_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=400)),
                ('department_name', models.CharField(max_length=400)),
                ('job_description', ckeditor.fields.RichTextField()),
                ('experience', models.CharField(max_length=400)),
                ('loaction', models.CharField(max_length=400)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('last_date_applay', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=400)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post', to=settings.AUTH_USER_MODEL)),
                ('careers_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexus_health.careers_page')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Application_Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phoneno', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='careers/Job_Application_Forms')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post', to='nexus_health.job_post')),
            ],
        ),
    ]
